//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevitDevelop.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AutoCutRebarBeamV2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AutoCutRebarBeamV2() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RevitDevelop.Properties.Langs.AutoCutRebarBeamV2", typeof(AutoCutRebarBeamV2).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance Lap To Lap.
        /// </summary>
        public static string REBAR_BEAM_CUT_DISTANCE_LAP_TO_LAP {
            get {
                return ResourceManager.GetString("REBAR_BEAM_CUT_DISTANCE_LAP_TO_LAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REBAR_BEAM_CUT_EXCEPTION_A_OVER_LIMIT.
        /// </summary>
        public static string REBAR_BEAM_CUT_EXCEPTION_A_OVER_LIMIT {
            get {
                return ResourceManager.GetString("REBAR_BEAM_CUT_EXCEPTION_A_OVER_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REBAR_BEAM_CUT_EXCEPTION_B_OVER_LIMIT.
        /// </summary>
        public static string REBAR_BEAM_CUT_EXCEPTION_B_OVER_LIMIT {
            get {
                return ResourceManager.GetString("REBAR_BEAM_CUT_EXCEPTION_B_OVER_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebar Group.
        /// </summary>
        public static string REBAR_BEAM_CUT_GROUP {
            get {
                return ResourceManager.GetString("REBAR_BEAM_CUT_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebar Group Cut.
        /// </summary>
        public static string REBAR_BEAM_CUT_GROUP_CUT {
            get {
                return ResourceManager.GetString("REBAR_BEAM_CUT_GROUP_CUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupler.
        /// </summary>
        public static string REBAR_BEAM_CUT_LAP_COUPLER {
            get {
                return ResourceManager.GetString("REBAR_BEAM_CUT_LAP_COUPLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lap Length.
        /// </summary>
        public static string REBAR_BEAM_CUT_LAP_LENGTH {
            get {
                return ResourceManager.GetString("REBAR_BEAM_CUT_LAP_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lap Option.
        /// </summary>
        public static string REBAR_BEAM_CUT_LAP_OPTION {
            get {
                return ResourceManager.GetString("REBAR_BEAM_CUT_LAP_OPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lap Type.
        /// </summary>
        public static string REBAR_BEAM_CUT_LAP_TYPE {
            get {
                return ResourceManager.GetString("REBAR_BEAM_CUT_LAP_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weld.
        /// </summary>
        public static string REBAR_BEAM_CUT_LAP_WELD {
            get {
                return ResourceManager.GetString("REBAR_BEAM_CUT_LAP_WELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length Cut.
        /// </summary>
        public static string REBAR_BEAM_CUT_LENGTH_CUT {
            get {
                return ResourceManager.GetString("REBAR_BEAM_CUT_LENGTH_CUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebar Position.
        /// </summary>
        public static string REBAR_BEAM_CUT_POSITION {
            get {
                return ResourceManager.GetString("REBAR_BEAM_CUT_POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebar Bottom.
        /// </summary>
        public static string REBAR_BEAM_CUT_POSITION_BOTTOM {
            get {
                return ResourceManager.GetString("REBAR_BEAM_CUT_POSITION_BOTTOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebar Top.
        /// </summary>
        public static string REBAR_BEAM_CUT_POSITION_TOP {
            get {
                return ResourceManager.GetString("REBAR_BEAM_CUT_POSITION_TOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoCutRebarBeamV2View.
        /// </summary>
        public static string REBAR_BEAM_CUT_TITLE {
            get {
                return ResourceManager.GetString("REBAR_BEAM_CUT_TITLE", resourceCulture);
            }
        }
    }
}
