//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevitDevelop.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CreateGridView {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateGridView() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RevitDevelop.Properties.Langs.CreateGridView", typeof(CreateGridView).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting Grid Angle.
        /// </summary>
        public static string SETTING_GRID_ANGLE {
            get {
                return ResourceManager.GetString("SETTING_GRID_ANGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting Grid X Name.
        /// </summary>
        public static string SETTING_GRID_X_NAME {
            get {
                return ResourceManager.GetString("SETTING_GRID_X_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting Grid X Value.
        /// </summary>
        public static string SETTING_GRID_X_VALUE {
            get {
                return ResourceManager.GetString("SETTING_GRID_X_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting Grid Y Name.
        /// </summary>
        public static string SETTING_GRID_Y_NAME {
            get {
                return ResourceManager.GetString("SETTING_GRID_Y_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting Grid Y Value.
        /// </summary>
        public static string SETTING_GRID_Y_VALUE {
            get {
                return ResourceManager.GetString("SETTING_GRID_Y_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting Grid Z Name.
        /// </summary>
        public static string SETTING_GRID_Z_NAME {
            get {
                return ResourceManager.GetString("SETTING_GRID_Z_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting Grid Z Value.
        /// </summary>
        public static string SETTING_GRID_Z_VALUE {
            get {
                return ResourceManager.GetString("SETTING_GRID_Z_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Grid View.
        /// </summary>
        public static string TOOL_CREATE_GRID_TITLE {
            get {
                return ResourceManager.GetString("TOOL_CREATE_GRID_TITLE", resourceCulture);
            }
        }
    }
}
